### ISSUE TITLE
New release to support new soul break types

### ISSUE THREAD

**Issue by Endracion** [rk-squared/rk-squared#13]
I see there are quite a few updates in the files, but no new release.

Many soul break types are no longer supported in the 2.6.0 version, and I cannot build the app since it requires a pro fontawesome license.

Is there a new release coming or a workaround?

**Comment by joshkel** [comment]
Thanks for the feedback.

I've been working on a new release (as you noticed) and am trying to get the application easier to maintain, but I haven't had time to resolve a few remaining issues. I'm planning on a new release in the first half of next week.

**Comment by Endracion** [comment]
Thanks for letting me know! Makes sense then, and no rush - appreciate your work on this.
